import type { Athlete, TrainingPlan } from './types'

export const MOCK_ATHLETES: Athlete[] = [
  {
    id: '1',
    name: 'Carlos Mendoza',
    age: 24,
    sport: 'Atletismo',
    goal: 'Preparación para maratón en octubre',
    email: 'carlos@atletismo.com',
    phone: '+52 55 1234 5678',
    active: true,
    joinedAt: '2026-01-15',
    gender: 'hombre',
    status: 'activo',
  },
  {
    id: '2',
    name: 'Ana Torres',
    age: 28,
    sport: 'CrossFit',
    goal: 'Ganar masa muscular y mejorar resistencia',
    email: 'ana@crossfit.com',
    active: true,
    joinedAt: '2026-02-20',
    gender: 'mujer',
    status: 'por_trabajar',
  },
  {
    id: '3',
    name: 'Luis Ramírez',
    age: 21,
    sport: 'Fútbol',
    goal: 'Mejorar velocidad y fuerza explosiva para temporada',
    email: 'luis@futbol.com',
    active: true,
    joinedAt: '2026-03-10',
    gender: 'hombre',
    status: 'trabajando',
  },
]

export const MOCK_PLANS: TrainingPlan[] = [
  {
    id: 'p1',
    name: 'Base Aeróbica – 4 semanas',
    athleteId: '1',
    startDate: '2026-06-16',
    endDate: '2026-07-13',
    createdAt: '2026-06-10',
    weeks: [
      {
        id: 'w1',
        weekNumber: 1,
        days: [
          {
            id: 'd1',
            date: '2026-06-16',
            dayLabel: 'Lunes 16 jun',
            exercises: [
              {
                id: 'e1',
                type: 'cardio',
                name: 'Carrera continua',
                distance: 8,
                duration: 45,
                pace: '5:30 min/km',
                heartRateZone: 2,
                notes: 'Ritmo conversacional, no acelerar',
              },
              {
                id: 'e2',
                type: 'strength',
                name: 'Sentadillas con barra',
                sets: 3,
                reps: 12,
                weight: 60,
                rest: 90,
              },
              {
                id: 'e3',
                type: 'strength',
                name: 'Peso muerto',
                sets: 3,
                reps: 8,
                weight: 80,
                rest: 120,
                notes: 'Mantener espalda recta',
              },
            ],
          },
          {
            id: 'd2',
            date: '2026-06-18',
            dayLabel: 'Miércoles 18 jun',
            exercises: [
              {
                id: 'e4',
                type: 'cardio',
                name: 'Intervalos 400m',
                distance: 6,
                duration: 35,
                notes: '8 × 400m con 90 seg de recuperación',
              },
            ],
          },
          {
            id: 'd3',
            date: '2026-06-20',
            dayLabel: 'Viernes 20 jun',
            exercises: [
              {
                id: 'e5',
                type: 'cardio',
                name: 'Carrera larga',
                distance: 14,
                duration: 80,
                pace: '5:45 min/km',
                heartRateZone: 2,
                notes: 'Hidratarse cada 20 min',
              },
              {
                id: 'e6',
                type: 'strength',
                name: 'Estocadas',
                sets: 3,
                reps: 10,
                weight: 20,
                rest: 60,
                notes: '10 por cada pierna',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'p2',
    name: 'Fuerza Base – 3 semanas',
    athleteId: '1',
    startDate: '2026-05-12',
    endDate: '2026-06-01',
    createdAt: '2026-05-08',
    weeks: [
      {
        id: 'w2',
        weekNumber: 1,
        days: [
          {
            id: 'd4',
            date: '2026-05-12',
            dayLabel: 'Lunes 12 may',
            exercises: [
              {
                id: 'e7',
                type: 'strength',
                name: 'Press de banca',
                sets: 4,
                reps: 8,
                weight: 75,
                rest: 120,
              },
              {
                id: 'e8',
                type: 'strength',
                name: 'Remo con barra',
                sets: 4,
                reps: 10,
                weight: 60,
                rest: 90,
              },
            ],
          },
        ],
      },
    ],
  },
]
